apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: "{{ $.Values.odf.channel }}"
{{- if $.Values.odf.startingCSV }}
  startingCSV: "{{ $.Values.odf.startingCSV }}"
{{- end }}
  installPlanApproval: Automatic
  name: odf-operator
  source: "{{ $.Values.odf.catalogSource.name }}"
  sourceNamespace: openshift-storage