apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: "{{ $.Values.argocd.channel }}"
{{- if $.Values.argocd.startingCSV }}
  startingCSV: "{{ $.Values.argocd.startingCSV }}"
{{- end }}
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: "{{ $.Values.argocd.catalogSource.name }}"
  sourceNamespace: openshift-operators